
package com.thed.service.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZephyrSoapService", targetNamespace = "http://soap.service.thed.com/", wsdlLocation = "file:/C:/Users/Mohan.Kumar/Desktop/wsdl/zephyrsoapservice-v1.xml")
public class ZephyrSoapService_Service
    extends Service
{

    public final static URL ZEPHYRSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZEPHYRSOAPSERVICE_EXCEPTION;
    private final static QName ZEPHYRSOAPSERVICE_QNAME = new QName("http://soap.service.thed.com/", "ZephyrSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Mohan.Kumar/Desktop/wsdl/zephyrsoapservice-v1.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZEPHYRSOAPSERVICE_WSDL_LOCATION = url;
        ZEPHYRSOAPSERVICE_EXCEPTION = e;
    }

    public ZephyrSoapService_Service() {
        super(__getWsdlLocation(), ZEPHYRSOAPSERVICE_QNAME);
    }

    public ZephyrSoapService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZEPHYRSOAPSERVICE_QNAME, features);
    }

    public ZephyrSoapService_Service(URL wsdlLocation) {
        super(wsdlLocation, ZEPHYRSOAPSERVICE_QNAME);
    }

    public ZephyrSoapService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZEPHYRSOAPSERVICE_QNAME, features);
    }

    public ZephyrSoapService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZephyrSoapService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZephyrSoapService
     */
    @WebEndpoint(name = "ZephyrSoapServiceImplPort")
    public ZephyrSoapService getZephyrSoapServiceImplPort() {
        return super.getPort(new QName("http://soap.service.thed.com/", "ZephyrSoapServiceImplPort"), ZephyrSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZephyrSoapService
     */
    @WebEndpoint(name = "ZephyrSoapServiceImplPort")
    public ZephyrSoapService getZephyrSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.thed.com/", "ZephyrSoapServiceImplPort"), ZephyrSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZEPHYRSOAPSERVICE_EXCEPTION!= null) {
            throw ZEPHYRSOAPSERVICE_EXCEPTION;
        }
        return ZEPHYRSOAPSERVICE_WSDL_LOCATION;
    }

}
